In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from statistics import mean, stdev, variance, median

In [ ]:
#RA is Right Ankle Sensor
RA128 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/05. filtered_walk_label_subject128_RightAnkle_Accelerometer.csv')
RA129 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/11. filtered_walk_label_subject129_RightAnkle_Accelerometer.csv')
RA143 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/17. filtered_walk_label_subject143_RightAnkle_Accelerometer.csv')
RA153 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/23. filtered_walk_label_subject153_RightAnkle_Accelerometer.csv')
RA154 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/29. filtered_walk_label_subject154_RightAnkle_Accelerometer.csv')
RA162 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/35. filtered_walk_label_subject162_RightAnkle_Accelerometer.csv')
RA165 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/41. filtered_walk_label_subject165_RightAnkle_Accelerometer.csv')
RA177 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/47. filtered_walk_label_subject177_RightAnkle_Accelerometer.csv')
RA197 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/53. filtered_walk_label_subject197_RightAnkle_Accelerometer.csv')
RA260 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/59. filtered_walk_label_subject260_RightAnkle_Accelerometer.csv')
RA525 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/65. filtered_walk_label_subject525_RightAnkle_Accelerometer.csv')
RA914 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/71. filtered_walk_label_subject914_RightAnkle_Accelerometer.csv')

#BH is Back Hip Sensor
BH128 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/03. filtered_walk_label_subject128_BackHip_Accelerometer.csv')
BH129 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/09. filtered_walk_label_subject129_BackHip_Accelerometer.csv')
BH143 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/15. filtered_walk_label_subject143_BackHip_Accelerometer.csv')
BH153 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/21. filtered_walk_label_subject153_BackHip_Accelerometer.csv')
BH154 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/27. filtered_walk_label_subject154_BackHip_Accelerometer.csv')
BH162 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/33. filtered_walk_label_subject162_BackHip_Accelerometer.csv')
BH165 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/39. filtered_walk_label_subject165_BackHip_Accelerometer.csv')
BH177 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/45. filtered_walk_label_subject177_BackHip_Accelerometer.csv')
BH197 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/51. filtered_walk_label_subject197_BackHip_Accelerometer.csv')
BH260 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/57. filtered_walk_label_subject260_BackHip_Accelerometer.csv')
BH525 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/63. filtered_walk_label_subject525_BackHip_Accelerometer.csv')
BH914 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/69. filtered_walk_label_subject914_BackHip_Accelerometer.csv')


In [ ]:
#Format User's data frames to remove unnecesary columns and rows. Will only be using 200 rows
#User128 (1) Back Hip
BH128[['x','y','z']] = BH128[['lateral', 'vertical','anterior']]
BH128 = BH128.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds','timestamp0500'], axis=1)
BH128['ID'] = BH128['label']
BH128 = BH128.drop(labels='label', axis=1)
BH128['ID'] = '128'

#User129(2) Back Hip
BH129[['x', 'y', 'z']] = BH129[['lateral', 'vertical', 'anterior']]
BH129 = BH129.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH129['ID'] = BH129['label']
BH129 = BH129.drop(labels='label', axis=1)
BH129['ID'] = '129'

#User143(3) Back Hip
BH143[['x', 'y', 'z']] = BH143[['lateral', 'vertical', 'anterior']]
BH143 = BH143.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH143['ID'] = BH143['label']
BH143 = BH143.drop(labels='label', axis=1)
BH143['ID'] = '143'

#User153(4) Back Hip
BH153[['x', 'y', 'z']] = BH153[['lateral', 'vertical', 'anterior']]
BH153 = BH153.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH153['ID'] = BH153['label']
BH153 = BH153.drop(labels='label', axis=1)
BH153['153'] = '153'

#User154(5) Back Hip
BH154[['x', 'y', 'z']] = BH154[['lateral', 'vertical', 'anterior']]
BH154 = BH154.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH154['ID'] = BH154['label']
BH154 = BH154.drop(labels='label', axis=1)
BH154['ID'] = '154'

#User162(6) Back Hip
BH162[['x', 'y', 'z']] = BH162[['lateral', 'vertical', 'anterior']]
BH162 = BH162.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH162['ID'] = BH162['label']
BH162 = BH162.drop(labels='label', axis=1)
BH162['ID'] = '162'

#User165(7) Back Hip
BH165[['x', 'y', 'z']] = BH165[['lateral', 'vertical', 'anterior']]
BH165 = BH165.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH165['ID'] = BH165['label']
BH165 = BH165.drop(labels='label', axis=1)
BH165['ID'] = '165'

#User177(8) Back Hip
BH177[['x', 'y', 'z']] = BH177[['lateral', 'vertical', 'anterior']]
BH177 = BH177.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH177['ID'] = BH177['label']
BH177 = BH177.drop(labels='label', axis=1)
BH177['ID'] = '177'

#User197(9) Back Hip
BH197[['x', 'y', 'z']] = BH197[['lateral', 'vertical', 'anterior']]
BH197 = BH197.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH197['ID'] = BH197['label']
BH197 = BH197.drop(labels='label', axis=1)
BH197['ID'] = '197'

#User260(10) Back Hip
BH260[['x', 'y', 'z']] = BH260[['lateral', 'vertical', 'anterior']]
BH260 = BH260.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH260['ID'] = BH260['label']
BH260 = BH260.drop(labels='label', axis=1)
BH260['ID'] = '260'

#User525(11) Back Hip
BH525[['x', 'y', 'z']] = BH525[['lateral', 'vertical', 'anterior']]
BH525 = BH525.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH525['ID'] = BH525['label']
BH525 = BH525.drop(labels='label', axis=1)
BH525['ID'] = '525'

#User914(12) Back Hip
BH914[['x', 'y', 'z']] = BH914[['lateral', 'vertical', 'anterior']]
BH914 = BH914.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH914['ID'] = BH914['label']
BH914 = BH914.drop(labels='label', axis=1)
BH914['ID'] = '914'

##############################################################################################################################################

#User128 (1) Right Ankle
RA128[['x','y','z']] = RA128[['lateral', 'vertical','anterior']]
RA128 = RA128.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds','timestamp0500'], axis=1)
RA128['ID'] = RA128['label']
RA128 = RA128.drop(labels='label', axis=1)
RA128['ID'] = '128'

#User129(2) Right Ankle
RA129[['x', 'y', 'z']] = RA129[['lateral', 'vertical', 'anterior']]
RA129 = RA129.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA129['ID'] = RA129['label']
RA129 = RA129.drop(labels='label', axis=1)
RA129['ID'] = '129'

#User143(3) Right Ankle
RA143[['x', 'y', 'z']] = RA143[['lateral', 'vertical', 'anterior']]
RA143 = RA143.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA143['ID'] = RA143['label']
RA143 = RA143.drop(labels='label', axis=1)
RA143['ID'] = '143'

#User153(4) Right Ankle
RA153[['x', 'y', 'z']] = RA153[['lateral', 'vertical', 'anterior']]
RA153 = RA153.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA153['ID'] = RA153['label']
RA153 = RA153.drop(labels='label', axis=1)
RA153['153'] = '153'

#User154(5) Right Ankle
RA154[['x', 'y', 'z']] = RA154[['lateral', 'vertical', 'anterior']]
RA154 = RA154.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA154['ID'] = RA154['label']
RA154 = RA154.drop(labels='label', axis=1)
RA154['ID'] = '154'

#User162(6) Right Ankle
RA162[['x', 'y', 'z']] = RA162[['lateral', 'vertical', 'anterior']]
RA162 = RA162.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA162['ID'] = RA162['label']
RA162 = RA162.drop(labels='label', axis=1)
RA162['ID'] = '162'

#User165(7) Right Ankle
RA165[['x', 'y', 'z']] = RA165[['lateral', 'vertical', 'anterior']]
RA165 = RA165.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA165['ID'] = RA165['label']
RA165 = RA165.drop(labels='label', axis=1)
RA165['ID'] = '165'

#User177(8) Right Ankle
RA177[['x', 'y', 'z']] = RA177[['lateral', 'vertical', 'anterior']]
RA177 = RA177.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA177['ID'] = RA177['label']
RA177 = RA177.drop(labels='label', axis=1)
RA177['ID'] = '177'

#User197(9) Right Ankle
RA197[['x', 'y', 'z']] = RA197[['lateral', 'vertical', 'anterior']]
RA197 = RA197.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA197['ID'] = RA197['label']
RA197 = RA197.drop(labels='label', axis=1)
RA197['ID'] = '197'

#User260(10) Right Ankle
RA260[['x', 'y', 'z']] = RA260[['lateral', 'vertical', 'anterior']]
RA260 = RA260.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
BH260['ID'] = RA260['label']
RA260 = RA260.drop(labels='label', axis=1)
RA260['ID'] = '260'

#User525(11) Right Ankle
RA525[['x', 'y', 'z']] = RA525[['lateral', 'vertical', 'anterior']]
RA525 = RA525.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA525['ID'] = RA525['label']
RA525 = RA525.drop(labels='label', axis=1)
RA525['ID'] = '525'

#User914(12) Right Ankle
RA914[['x', 'y', 'z']] = RA914[['lateral', 'vertical', 'anterior']]
RA914 = RA914.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
RA914['ID'] = RA914['label']
RA914 = RA914.drop(labels='label', axis=1)
RA914['ID'] = '914'

In [ ]:
#Function for extracting features from the different data frames
#Features are: Mean, STD, Skewness, Kurtosis, Variance, IQR
def features(dataframe):
  count = 0
  #Store mean values
  x_mean = []
  y_mean = []
  z_mean = []
  #Store standard deviation values
  x_std = []
  y_std = []
  z_std = []
  #Store max
  x_max = []
  y_max = []
  z_max = []
  #Store min
  x_min = []
  y_min = []
  z_min = []

  #Store Median
  x_med = []
  y_med = []
  z_med = []
  #List of all features extracted
  feature_extraction = []


  for i in range(len(dataframe)):
    if count != 99:
      #Append to mean list
      x_mean.append(dataframe['x'][i])
      y_mean.append(dataframe['y'][i])
      z_mean.append(dataframe['z'][i])

      #Append to standard deviation list
      x_std.append(dataframe['x'][i])
      y_std.append(dataframe['y'][i])
      z_std.append(dataframe['z'][i])

      #Append to max
      x_max.append(dataframe['x'][i])
      y_max.append(dataframe['y'][i])
      z_max.append(dataframe['z'][i])

      #Append to min
      x_min.append(dataframe['x'][i])
      y_min.append(dataframe['y'][i])
      z_min.append(dataframe['z'][i])

      #Append to Median
      x_med.append(dataframe['x'][i])
      y_med.append(dataframe['y'][i])
      z_med.append(dataframe['z'][i])


      count = count + 1
    else:
      #Calculate mean
      x_mean = mean(x_mean)
      y_mean = mean(y_mean)
      z_mean = mean(z_mean)

      #Calculate standar deviation
      x_std = stdev(x_std)
      y_std = stdev(y_std)
      z_std = stdev(z_std)

      #Calculate max
      x_max = max(x_max)
      y_max = max(y_max)
      z_max = max(z_max)

      #Calculate min
      x_min = min(x_min)
      y_min = min(y_min)
      z_min = min(z_min)

      #Calculate median
      x_med = median(x_med)
      y_med = median(y_med)
      z_med = median(z_med)

      #Store features in tuple then store tuple in feature_extracion list
      data_tuple = (x_mean, y_mean, z_mean, x_std, y_std, z_std, x_max, y_max, z_max, x_min, y_min, z_min, x_med, y_med, z_med)
      feature_extraction.append(data_tuple)

      #Clear lists to proceed to the next 5 elements
      x_mean = []
      y_mean = []
      z_mean = []

      x_std = []
      y_std = []
      z_std = []

      x_max = []
      y_max = []
      z_max = []

      x_min = []
      y_min = []
      z_min = []

      x_med = []
      y_med = []
      z_med = []

      #Reset counter
      count = 0

  return feature_extraction #returns tuple list


In [ ]:
#RA is Right Ankle Sensor
ra1 = features(RA128)
ra2 = features(RA129)
ra3 = features(RA143)
ra4 = features(RA153)
ra5 = features(RA154)
ra6 = features(RA162)
ra7 = features(RA165)
ra8 = features(RA177)
ra9 = features(RA197)
ra10 = features(RA260)
ra11 = features(RA525)
ra12 = features(RA914)

#BH is Back Hip Sensor
bh1 = features(BH128)
bh2 = features(BH129)
bh3 = features(BH143)
bh4 = features(BH153)
bh5 = features(BH154)
bh6 = features(BH162)
bh7 = features(BH165)
bh8 = features(BH177)
bh9 = features(BH197)
bh10 = features(BH260)
bh11 = features(BH525)
bh12 = features(BH914)


In [ ]:
ra1 = pd.DataFrame(ra1)
ra2 = pd.DataFrame(ra2)
ra3 = pd.DataFrame(ra3)
ra4 = pd.DataFrame(ra4)
ra5 = pd.DataFrame(ra5)
ra6 = pd.DataFrame(ra6)
ra7 = pd.DataFrame(ra7)
ra8 = pd.DataFrame(ra8)
ra9 = pd.DataFrame(ra9)
ra10 = pd.DataFrame(ra10)
ra11 = pd.DataFrame(ra11)
ra12 = pd.DataFrame(ra12)

bh1 = pd.DataFrame(bh1)
bh2 = pd.DataFrame(bh2)
bh3 = pd.DataFrame(bh3)
bh4 = pd.DataFrame(bh4)
bh5 = pd.DataFrame(bh5)
bh6 = pd.DataFrame(bh6)
bh7 = pd.DataFrame(bh7)
bh8 = pd.DataFrame(bh8)
bh9 = pd.DataFrame(bh9)
bh10 = pd.DataFrame(bh10)
bh11 = pd.DataFrame(bh11)
bh12 = pd.DataFrame(bh12)


In [ ]:
#Rename columns to their feature names mean, std, max, min, median for both sensors' data frames
#Right Ankle Sensor
ra1[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra1[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra1 = ra1.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra1['ID'] = 128

ra2[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra2[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra2 = ra2.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra2['ID'] = 129

ra3[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra3[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra3 = ra3.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra3['ID'] = 143

ra4[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra4[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra4 = ra4.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra4['ID'] = 153

ra5[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra5[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra5 = ra5.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra5['ID'] = 154

ra6[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra6[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra6 = ra6.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra6['ID'] = 162

ra7[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra7[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra7 = ra7.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra7['ID'] = 165

ra8[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra8[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra8 = ra8.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra8['ID'] = 177

ra9[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra9[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra9 = ra9.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra9['ID'] = 197

ra10[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra10[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra10 = ra10.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra10['ID'] = 260

ra11[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra11[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra11 = ra11.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra11['ID'] = 525

ra12[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = ra12[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
ra12 = ra12.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
ra12['ID'] = 914

#Back Hip Sensor '

bh1[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh1[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh1 = bh1.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh1['ID'] = 128

bh2[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh2[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh2 = bh2.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh2['ID'] = 129

bh3[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh3[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh3 = bh3.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh3['ID'] = 143

bh4[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh4[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh4 = bh4.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh4['ID'] = 153

bh5[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh5[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh5 = bh5.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh5['ID'] = 154

bh6[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh6[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh6 = bh6.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh6['ID'] = 162

bh7[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh7[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh7 = bh7.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh7['ID'] = 165

bh8[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh8[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh8 = bh8.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh8['ID'] = 177

bh9[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh9[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh9 = bh9.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh9['ID'] = 197

bh10[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh10[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh10 = bh10.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh10['ID'] = 260

bh11[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh11[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh11 = bh11.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh11['ID'] = 525

bh12[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'X_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = bh12[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
bh12 = bh12.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
bh12['ID'] = 914


In [ ]:
framesra = ra1, ra2, ra3, ra4, ra5, ra6, ra7, ra8, ra9, ra10, ra11, ra12
framesbh =  bh1, bh2, bh3, bh4, bh5, bh6, bh7, bh8, bh9, bh10, bh11, bh12

In [ ]:
UserDFRA = pd.concat(framesra, axis=0, ignore_index=True )
UserDFBH = pd.concat(framesbh, axis=0, ignore_index=True)

In [ ]:
UserDF = pd.concat([UserDFRA, UserDFBH], keys=['RA', 'BH'], axis=0, ignore_index=True)

In [ ]:
UserDF

x_mean    y_mean    z_mean     x_std     y_std     z_std  x_max  \
0     1.173192  0.438121  0.164333  0.887049  1.094370  0.608954  5.591   
1     1.336869  0.397263  0.230919  0.867069  1.229847  0.684139  4.110   
2     1.352273  0.399202  0.224101  0.929369  1.216094  0.711469  4.545   
3     1.333394  0.374859  0.265727  0.978712  0.979895  0.657420  6.945   
4     1.372596  0.362232  0.250798  1.123525  1.149011  0.705174  7.231   
...        ...       ...       ...       ...       ...       ...    ...   
8525  0.899960 -0.053626  0.419172  0.260252  0.184183  0.255411  1.431   
8526  0.907071 -0.045535  0.415949  0.248308  0.191236  0.242951  1.489   
8527  0.890545 -0.028495  0.391646  0.251432  0.159956  0.240598  1.439   
8528  0.875303 -0.047566  0.366081  0.249060  0.175357  0.210105  1.442   
8529  0.866152 -0.045879  0.372293  0.255528  0.186167  0.215546  1.500   

      y_max  z_max  X_min  y_min  z_min  x_med  y_med  z_med   ID  
0     4.922  3.311 -1.867 -0.900 -1.469  1.027  0.216  0.108  128  
1     6.472  3.154 -0.180 -1.878 -1.527  1.043  0.202  0.168  128  
2     5.402  3.019 -0.330 -1.366 -2.249  1.059  0.199  0.149  128  
3     3.480  2.883 -0.344 -1.173 -1.896  1.095  0.218  0.193  128  
4     4.472  3.624 -1.128 -1.515 -2.229  1.110  0.202  0.222  128  
...     ...    ...    ...    ...    ...    ...    ...    ...  ...  
8525  0.263  1.010  0.515 -0.589 -0.007  0.832 -0.009  0.345  914  
8526  0.443  0.996  0.486 -0.592  0.085  0.845 -0.008  0.349  914  
8527  0.351  0.973  0.542 -0.538  0.037  0.779 -0.020  0.298  914  
8528  0.435  0.952  0.538 -0.625  0.026  0.773 -0.016  0.318  914  
8529  0.494  0.979  0.484 -0.701  0.085  0.775 -0.003  0.283  914  

[8530 rows x 16 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
X = UserDF.drop(labels='ID', axis=1)
y = UserDF['ID']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()

In [ ]:
scaled_X_train = scaler.fit_transform(X_train)

In [ ]:
scaled_X_test = scaler.transform(X_test)

In [ ]:
knn_model = KNeighborsClassifier(n_neighbors=1)

In [ ]:
model = knn_model.fit(scaled_X_train, y_train)

In [ ]:
pred = model.predict(scaled_X_test)

In [ ]:
print(confusion_matrix(y_test, pred))

[[141   1   0   1   0   0   1   0   0   4   0   7]
 [  0 133   0   0   0   0   0   0   0   0   0   0]
 [  1   0 142   0   0   2   1   2   0   2   0   0]
 [  4   0   0 120   1   0   2   0   2   3   0   2]
 [  0   0   0   1 130   1   1   0   0   1   0   1]
 [  1   0   5   0   1 142   1   0   0   0   0   0]
 [  0   0   0   0   2   1 131   0   0   0   0   1]
 [  0   0   1   0   0   0   0 116   0   0   0   0]
 [  1   2   0   1   3   1   0   1 141   0   1   0]
 [  6   1   1   2   2   0   0   1   0 120   0   1]
 [  1   0   0   0   2   1   0   1   0   1 137   0]
 [  8   0   0   3   0   0   1   0   2   1   0 154]]


In [ ]:
print(accuracy_score(y_test, pred) * 100)

94.19695193434936


In [ ]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

         128       0.87      0.91      0.89       155
         129       0.97      1.00      0.99       133
         143       0.95      0.95      0.95       150
         153       0.94      0.90      0.92       134
         154       0.92      0.96      0.94       135
         162       0.96      0.95      0.95       150
         165       0.95      0.97      0.96       135
         177       0.96      0.99      0.97       117
         197       0.97      0.93      0.95       151
         260       0.91      0.90      0.90       134
         525       0.99      0.96      0.98       143
         914       0.93      0.91      0.92       169

    accuracy                           0.94      1706
   macro avg       0.94      0.94      0.94      1706
weighted avg       0.94      0.94      0.94      1706

