In [334]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from statistics import mean, stdev, variance
from scipy.stats import skew, kurtosis

In [335]:
User128 = pd.read_csv('/content/drive/MyDrive/Project Data Set/1_3_data_set/First_3_users_data/03. filtered_walk_label_subject128_BackHip_Accelerometer.csv')
User129 = pd.read_csv('/content/drive/MyDrive/Project Data Set/1_3_data_set/First_3_users_data/09. filtered_walk_label_subject129_BackHip_Accelerometer.csv')
User143 = pd.read_csv('/content/drive/MyDrive/Project Data Set/1_3_data_set/First_3_users_data/15. filtered_walk_label_subject143_BackHip_Accelerometer.csv')
User153 = pd.read_csv('/content/drive/MyDrive/Project Data Set/4_6_data_set/21. filtered_walk_label_subject153_BackHip_Accelerometer.csv')
User154 = pd.read_csv('/content/drive/MyDrive/Project Data Set/4_6_data_set/27. filtered_walk_label_subject154_BackHip_Accelerometer.csv')
User162 = pd.read_csv('/content/drive/MyDrive/Project Data Set/4_6_data_set/33. filtered_walk_label_subject162_BackHip_Accelerometer.csv')
User165 = pd.read_csv('/content/drive/MyDrive/Project Data Set/7_9_data_set/39. filtered_walk_label_subject165_BackHip_Accelerometer.csv')
User177 = pd.read_csv('/content/drive/MyDrive/Project Data Set/7_9_data_set/45. filtered_walk_label_subject177_BackHip_Accelerometer.csv')
User197 = pd.read_csv('/content/drive/MyDrive/Project Data Set/7_9_data_set/51. filtered_walk_label_subject197_BackHip_Accelerometer.csv')
User260 = pd.read_csv('/content/drive/MyDrive/Project Data Set/10_12_data_set/57. filtered_walk_label_subject260_BackHip_Accelerometer.csv')
User525 = pd.read_csv('/content/drive/MyDrive/Project Data Set/10_12_data_set/63. filtered_walk_label_subject525_BackHip_Accelerometer.csv')
User914 = pd.read_csv('/content/drive/MyDrive/Project Data Set/10_12_data_set/69. filtered_walk_label_subject914_BackHip_Accelerometer.csv')

In [336]:
#Format User's data frames to remove unnecesary columns and rows. Will only be using 200 rows
#User128 (1)
User128[['x','y','z']] = User128[['lateral', 'vertical','anterior']]
User128 = User128.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds','timestamp0500'], axis=1)[:10000]
User128['ID'] = User128['label']
User128 = User128.drop(labels='label', axis=1)
User128['ID'] = '128'

#User129(2)
User129[['x', 'y', 'z']] = User129[['lateral', 'vertical', 'anterior']]
User129 = User129.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User129['ID'] = User129['label']
User129 = User129.drop(labels='label', axis=1)
User129['ID'] = '129'

#User143(3)
User143[['x', 'y', 'z']] = User143[['lateral', 'vertical', 'anterior']]
User143 = User143.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User143['ID'] = User143['label']
User143 = User143.drop(labels='label', axis=1)
User143['ID'] = '143'

#User153(4)
User153[['x', 'y', 'z']] = User153[['lateral', 'vertical', 'anterior']]
User153 = User153.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User153['ID'] = User153['label']
User153 = User153.drop(labels='label', axis=1)
User153['153'] = '153'

#User154(5)
User154[['x', 'y', 'z']] = User154[['lateral', 'vertical', 'anterior']]
User154 = User154.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User154['ID'] = User154['label']
User154 = User154.drop(labels='label', axis=1)
User154['ID'] = '154'

#User162(6)
User162[['x', 'y', 'z']] = User162[['lateral', 'vertical', 'anterior']]
User162 = User162.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User162['ID'] = User162['label']
User162 = User162.drop(labels='label', axis=1)
User162['ID'] = '162'

#User165(7)
User165[['x', 'y', 'z']] = User165[['lateral', 'vertical', 'anterior']]
User165 = User165.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User165['ID'] = User165['label']
User165 = User165.drop(labels='label', axis=1)
User165['ID'] = '165'

#User177(8)
User177[['x', 'y', 'z']] = User177[['lateral', 'vertical', 'anterior']]
User177 = User177.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User177['ID'] = User177['label']
User177 = User177.drop(labels='label', axis=1)
User177['ID'] = '177'

#User197(9)
User197[['x', 'y', 'z']] = User197[['lateral', 'vertical', 'anterior']]
User197 = User197.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User197['ID'] = User197['label']
User197 = User197.drop(labels='label', axis=1)
User197['ID'] = '197'

#User260(10)
User260[['x', 'y', 'z']] = User260[['lateral', 'vertical', 'anterior']]
User260 = User260.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User260['ID'] = User260['label']
User260 = User260.drop(labels='label', axis=1)
User260['ID'] = '260'

#User525(11)
User525[['x', 'y', 'z']] = User525[['lateral', 'vertical', 'anterior']]
User525 = User525.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User525['ID'] = User525['label']
User525 = User525.drop(labels='label', axis=1)
User525['ID'] = '525'

#User914(12)
User914[['x', 'y', 'z']] = User914[['lateral', 'vertical', 'anterior']]
User914 = User914.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)[:10000]
User914['ID'] = User914['label']
User914 = User914.drop(labels='label', axis=1)
User914['ID'] = '914'

In [337]:
#Function for extracting features from the different data frames
#Features are: Mean, STD, Skewness, Kurtosis, Variance, IQR
def features(dataframe):
  count = 0
  #Store mean values
  x_mean = []
  y_mean = []
  z_mean = []
  #Store standard deviation values
  x_std = []
  y_std = []
  z_std = []
  #Store variance values
  x_var = []
  y_var = []
  z_var = []
  #Store Inter Quartile Range (IQR)
  x_iqr = []
  y_iqr = []
  z_iqr = []

  #Store Kurtosis
  x_kur = []
  y_kur = []
  z_kur = []
  #Store Skewness
  x_skw = []
  y_skw = []
  z_skw = []
  #List of all features extracted
  feature_extraction = []


  for i in range(len(dataframe)):
    if count != 4:
      #Append to mean list
      x_mean.append(dataframe['x'][i])
      y_mean.append(dataframe['y'][i])
      z_mean.append(dataframe['z'][i])

      #Append to standard deviation list
      x_std.append(dataframe['x'][i])
      y_std.append(dataframe['y'][i])
      z_std.append(dataframe['z'][i])

      #Append to variance list
      x_var.append(dataframe['x'][i])
      y_var.append(dataframe['y'][i])
      z_var.append(dataframe['z'][i])

      #Append to IQR list
      x_iqr.append(dataframe['x'][i])
      y_iqr.append(dataframe['y'][i])
      z_iqr.append(dataframe['z'][i])

      #Append to Skewness list
      x_skw.append(dataframe['x'][i])
      y_skw.append(dataframe['y'][i])
      z_skw.append(dataframe['z'][i])

      #Append to Kurtosis list
      x_kur.append(dataframe['x'][i])
      y_kur.append(dataframe['y'][i])
      z_kur.append(dataframe['z'][i])

      count = count + 1
    else:
      #Calculate mean
      x_mean = mean(x_mean)
      y_mean = mean(y_mean)
      z_mean = mean(z_mean)

      #Calculate standar deviation
      x_std = stdev(x_std)
      y_std = stdev(y_std)
      z_std = stdev(z_std)

      #Calculate Variance
      x_var = variance(x_var)
      y_var = variance(y_var)
      z_var = variance(z_var)

      #Calculate IQR
      q2,q1 = np.percentile(x_iqr, [75,25])
      q4,q3 = np.percentile(y_iqr, [75,25])
      q6,q5 = np.percentile(z_iqr, [75,25])

      x_iqr = q2-q1
      y_iqr = q4-q3
      z_iqr = q6-q5

      #Calculate Skewness
      x_skw = skew(x_skw, axis=0, bias=True)
      y_skw = skew(y_skw, axis=0, bias=True)
      z_skw = skew(z_skw, axis=0, bias=True)

      #Calculate Kurtosis
      x_kur = kurtosis(x_kur, axis=0, bias=True)
      y_kur = kurtosis(y_kur, axis=0, bias=True)
      z_kur = kurtosis(z_kur, axis=0, bias=True)

      #Store features in tuple then store tuple in feature_extracion list
      data_tuple = (x_mean, y_mean, z_mean, x_std, y_std, z_std, x_var, y_var, z_var, x_iqr, y_iqr, z_iqr, x_skw, y_skw, z_skw, x_kur, y_kur, z_kur)
      feature_extraction.append(data_tuple)

      #Clear lists to proceed to the next 5 elements
      x_mean = []
      y_mean = []
      z_mean = []

      x_std = []
      y_std = []
      z_std = []

      x_var = []
      y_var = []
      z_var = []

      x_iqr = []
      y_iqr = []
      z_iqr = []

      x_kur = []
      y_kur = []
      z_kur = []

      x_skw = []
      y_skw = []
      z_skw = []

      #Reset counter
      count = 0

  return feature_extraction #returns tuple list


In [338]:
x1 = features(User128)
x2 = features(User129)
x3 = features(User143)
x4 = features(User153)
x5 = features(User154)
x6 = features(User162)
x7 = features(User165)
x8 = features(User177)
x9 = features(User197)
x10 = features(User260)
x11 = features(User525)
x12 = features(User914)

In [339]:
x1 = pd.DataFrame(x1)
x2 = pd.DataFrame(x2)
x3 = pd.DataFrame(x3)
x4 = pd.DataFrame(x4)
x5 = pd.DataFrame(x5)
x6 = pd.DataFrame(x6)
x7 = pd.DataFrame(x7)
x8 = pd.DataFrame(x8)
x9 = pd.DataFrame(x9)
x10 = pd.DataFrame(x10)
x11 = pd.DataFrame(x11)
x12 = pd.DataFrame(x12)

In [340]:
#Rename columns to their feature names mean, std, var, iqr
x1[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x1[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x1 = x1.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x1['ID'] = 128

x2[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x2[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x2 = x2.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x2['ID'] = 129

x3[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x3[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x3 = x3.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x3['ID'] = 143

x4[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x4[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x4 = x4.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x4['ID'] = 153

x5[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x5[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x5 = x5.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x5['ID'] = 154

x6[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x6[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x6 = x6.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x6['ID'] = 162

x7[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x7[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x7 = x7.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x7['ID'] = 165

x8[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x8[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x8 = x8.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x8['ID'] = 177

x9[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x9[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x9 = x9.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x9['ID'] = 197

x10[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x10[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x10 = x10.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x10['ID'] = 260

x11[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x11[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x11 = x11.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x11['ID'] = 525

x12[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_var', 'y_var', 'z_var', 'x_iqr', 'y_iqr', 'z_iqr', 'x_skw', 'y_skw', 'z_skw', 'x_kur', 'y_kur', 'z_kur']] = x12[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
x12 = x12.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17], axis=1)
x12['ID'] = 914

In [341]:
frames = x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12

In [342]:
UserDF = pd.concat(frames, axis=0, ignore_index=True)

In [343]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [344]:
#New approach using Grid search to play with parameters and figure out the best ones
n_estimators=[64,100,128,200,400]
max_features=['sqrt', 'log2']
bootstrap=[True, False]
oob_score=[True, False]

param_grid = {'n_estimators': n_estimators, 'max_features': max_features, 'bootstrap': bootstrap, 'oob_score': oob_score}

In [345]:
UserDF.replace(np.nan, 0)
X = UserDF.drop(labels='ID', axis=1)
y = UserDF['ID']

In [346]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [361]:
rfc = RandomForestClassifier(n_estimators=275, bootstrap=True, oob_score=True, random_state=42)

In [348]:
#Using Grid Search
#grid = GridSearchCV(rfc,param_grid)

In [349]:
#grid.fit(X_train, y_train)

In [350]:
#grid.best_params_

In [351]:
#Comparing Grid Search CV oob_score False to a true one
#rfc2 = RandomForestClassifier(n_estimators=64, max_features='sqrt', bootstrap=True, oob_score=True)

In [352]:
#rfc2.fit(X_train,y_train)

In [353]:
#pred2 = rfc2.predict(X_test)

In [354]:
#print(accuracy_score(y_test, pred2)), rfc2.oob_score_

In [362]:
#Not using grid search
model = rfc.fit(X_train, y_train)

In [363]:
preds = rfc.predict(X_test)

In [364]:
print("Train score:", rfc.score(X_train, y_train) * 100)
print("Test score:", rfc.score(X_test, y_test) * 100)

Train score: 100.0
Test score: 62.0


In [365]:
print(confusion_matrix(y_test, preds))

[[237   0   3  10  11  12  18   6   7  25  10  26]
 [  0 443   0   0   2   0   0   0   2   0   0   0]
 [ 19   0 244  17   9  33  14  17   5  13  17  10]
 [ 31   1  10 185  15  10  33   9  20  21  14  36]
 [ 14   3  14  30 211   8  17  31  31  17   6  15]
 [ 17   0  22  10  18 236  24  17   9   9  27  10]
 [ 32   0  16  29  19  17 222   7   6  19  15  24]
 [ 11   7  13  17  19   8   2 256  28  12  11   6]
 [ 14   2   4  10  16   3  12  38 264  11  20   7]
 [ 74   1  11  38  14  23  30   3  14 129  28  33]
 [ 27   3  17  14   6  26  10   9  13  15 259   8]
 [ 23   0   2  21   5  14  21   0  12  15   4 290]]


In [366]:
print(accuracy_score(y_test, preds) * 100)

62.0


In [367]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

         128       0.47      0.65      0.55       365
         129       0.96      0.99      0.98       447
         143       0.69      0.61      0.65       398
         153       0.49      0.48      0.48       385
         154       0.61      0.53      0.57       397
         162       0.61      0.59      0.60       399
         165       0.55      0.55      0.55       406
         177       0.65      0.66      0.65       390
         197       0.64      0.66      0.65       401
         260       0.45      0.32      0.38       398
         525       0.63      0.64      0.63       407
         914       0.62      0.71      0.67       407

    accuracy                           0.62      4800
   macro avg       0.61      0.62      0.61      4800
weighted avg       0.62      0.62      0.62      4800

