In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from statistics import mean, stdev, variance, median

In [4]:
User128 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/03. filtered_walk_label_subject128_BackHip_Accelerometer.csv')
User129 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/09. filtered_walk_label_subject129_BackHip_Accelerometer.csv')
User143 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/1_3_data_set/First_3_users_data/15. filtered_walk_label_subject143_BackHip_Accelerometer.csv')
User153 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/21. filtered_walk_label_subject153_BackHip_Accelerometer.csv')
User154 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/27. filtered_walk_label_subject154_BackHip_Accelerometer.csv')
User162 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/4_6_data_set/33. filtered_walk_label_subject162_BackHip_Accelerometer.csv')
User165 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/39. filtered_walk_label_subject165_BackHip_Accelerometer.csv')
User177 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/45. filtered_walk_label_subject177_BackHip_Accelerometer.csv')
User197 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/7_9_data_set/51. filtered_walk_label_subject197_BackHip_Accelerometer.csv')
User260 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/57. filtered_walk_label_subject260_BackHip_Accelerometer.csv')
User525 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/63. filtered_walk_label_subject525_BackHip_Accelerometer.csv')
User914 = pd.read_csv('/content/drive/MyDrive/Gait_Authentication_Project/Project Data Set/10_12_data_set/69. filtered_walk_label_subject914_BackHip_Accelerometer.csv')

In [5]:
#Format User's data frames to remove unnecesary columns and rows. Will only be using 200 rows
#User128 (1)
User128[['x','y','z']] = User128[['lateral', 'vertical','anterior']]
User128 = User128.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds','timestamp0500'], axis=1)
User128['ID'] = User128['label']
User128 = User128.drop(labels='label', axis=1)
User128['ID'] = '128'

#User129(2)
User129[['x', 'y', 'z']] = User129[['lateral', 'vertical', 'anterior']]
User129 = User129.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User129['ID'] = User129['label']
User129 = User129.drop(labels='label', axis=1)
User129['ID'] = '129'

#User143(3)
User143[['x', 'y', 'z']] = User143[['lateral', 'vertical', 'anterior']]
User143 = User143.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User143['ID'] = User143['label']
User143 = User143.drop(labels='label', axis=1)
User143['ID'] = '143'

#User153(4)
User153[['x', 'y', 'z']] = User153[['lateral', 'vertical', 'anterior']]
User153 = User153.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User153['ID'] = User153['label']
User153 = User153.drop(labels='label', axis=1)
User153['153'] = '153'

#User154(5)
User154[['x', 'y', 'z']] = User154[['lateral', 'vertical', 'anterior']]
User154 = User154.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User154['ID'] = User154['label']
User154 = User154.drop(labels='label', axis=1)
User154['ID'] = '154'

#User162(6)
User162[['x', 'y', 'z']] = User162[['lateral', 'vertical', 'anterior']]
User162 = User162.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User162['ID'] = User162['label']
User162 = User162.drop(labels='label', axis=1)
User162['ID'] = '162'

#User165(7)
User165[['x', 'y', 'z']] = User165[['lateral', 'vertical', 'anterior']]
User165 = User165.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User165['ID'] = User165['label']
User165 = User165.drop(labels='label', axis=1)
User165['ID'] = '165'

#User177(8)
User177[['x', 'y', 'z']] = User177[['lateral', 'vertical', 'anterior']]
User177 = User177.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User177['ID'] = User177['label']
User177 = User177.drop(labels='label', axis=1)
User177['ID'] = '177'

#User197(9)
User197[['x', 'y', 'z']] = User197[['lateral', 'vertical', 'anterior']]
User197 = User197.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User197['ID'] = User197['label']
User197 = User197.drop(labels='label', axis=1)
User197['ID'] = '197'

#User260(10)
User260[['x', 'y', 'z']] = User260[['lateral', 'vertical', 'anterior']]
User260 = User260.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User260['ID'] = User260['label']
User260 = User260.drop(labels='label', axis=1)
User260['ID'] = '260'

#User525(11)
User525[['x', 'y', 'z']] = User525[['lateral', 'vertical', 'anterior']]
User525 = User525.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User525['ID'] = User525['label']
User525 = User525.drop(labels='label', axis=1)
User525['ID'] = '525'

#User914(12)
User914[['x', 'y', 'z']] = User914[['lateral', 'vertical', 'anterior']]
User914 = User914.drop(labels=['lateral', 'vertical', 'anterior', 'datetime', 'epocms', 'Unnamed: 0', 'elapseds', 'timestamp0500'], axis=1)
User914['ID'] = User914['label']
User914 = User914.drop(labels='label', axis=1)
User914['ID'] = '914'

In [6]:
#Function for extracting features from the different data frames
#Features are: Mean, STD, Skewness, Kurtosis, Variance, IQR
def features(dataframe):
  count = 0
  #Store mean values
  x_mean = []
  y_mean = []
  z_mean = []
  #Store standard deviation values
  x_std = []
  y_std = []
  z_std = []
  #Store max
  x_max = []
  y_max = []
  z_max = []
  #Store min
  x_min = []
  y_min = []
  z_min = []

  #Store Median
  x_med = []
  y_med = []
  z_med = []
  #List of all features extracted
  feature_extraction = []


  for i in range(len(dataframe)):
    if count != 99:
      #Append to mean list
      x_mean.append(dataframe['x'][i])
      y_mean.append(dataframe['y'][i])
      z_mean.append(dataframe['z'][i])

      #Append to standard deviation list
      x_std.append(dataframe['x'][i])
      y_std.append(dataframe['y'][i])
      z_std.append(dataframe['z'][i])

      #Append to max
      x_max.append(dataframe['x'][i])
      y_max.append(dataframe['y'][i])
      z_max.append(dataframe['z'][i])

      #Append to min
      x_min.append(dataframe['x'][i])
      y_min.append(dataframe['y'][i])
      z_min.append(dataframe['z'][i])

      #Append to Median
      x_med.append(dataframe['x'][i])
      y_med.append(dataframe['y'][i])
      z_med.append(dataframe['z'][i])


      count = count + 1
    else:
      #Calculate mean
      x_mean = mean(x_mean)
      y_mean = mean(y_mean)
      z_mean = mean(z_mean)

      #Calculate standar deviation
      x_std = stdev(x_std)
      y_std = stdev(y_std)
      z_std = stdev(z_std)

      #Calculate max
      x_max = max(x_max)
      y_max = max(y_max)
      z_max = max(z_max)

      #Calculate min
      x_min = min(x_min)
      y_min = min(y_min)
      z_min = min(z_min)

      #Calculate median
      x_med = median(x_med)
      y_med = median(y_med)
      z_med = median(z_med)

      #Store features in tuple then store tuple in feature_extracion list
      data_tuple = (x_mean, y_mean, z_mean, x_std, y_std, z_std, x_max, y_max, z_max, x_min, y_min, z_min, x_med, y_med, z_med)
      feature_extraction.append(data_tuple)

      #Clear lists to proceed to the next 5 elements
      x_mean = []
      y_mean = []
      z_mean = []

      x_std = []
      y_std = []
      z_std = []

      x_max = []
      y_max = []
      z_max = []

      x_min = []
      y_min = []
      z_min = []

      x_med = []
      y_med = []
      z_med = []

      #Reset counter
      count = 0

  return feature_extraction #returns tuple list


In [7]:
x1 = features(User128)
x2 = features(User129)
x3 = features(User143)
x4 = features(User153)
x5 = features(User154)
x6 = features(User162)
x7 = features(User165)
x8 = features(User177)
x9 = features(User197)
x10 = features(User260)
x11 = features(User525)
x12 = features(User914)

In [8]:
x1 = pd.DataFrame(x1)
x2 = pd.DataFrame(x2)
x3 = pd.DataFrame(x3)
x4 = pd.DataFrame(x4)
x5 = pd.DataFrame(x5)
x6 = pd.DataFrame(x6)
x7 = pd.DataFrame(x7)
x8 = pd.DataFrame(x8)
x9 = pd.DataFrame(x9)
x10 = pd.DataFrame(x10)
x11 = pd.DataFrame(x11)
x12 = pd.DataFrame(x12)

In [9]:
#Rename columns to their feature names mean, std, var, iqr
x1[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min','x_med', 'y_med', 'z_med']] = x1[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x1 = x1.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x1['ID'] = 128

x2[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x2[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x2 = x2.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x2['ID'] = 129

x3[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x3[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x3 = x3.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x3['ID'] = 143

x4[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x4[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x4 = x4.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x4['ID'] = 153

x5[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x5[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x5 = x5.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x5['ID'] = 154

x6[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x6[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x6 = x6.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x6['ID'] = 162

x7[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x7[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x7 = x7.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x7['ID'] = 165

x8[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x8[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x8 = x8.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x8['ID'] = 177

x9[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x9[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x9 = x9.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x9['ID'] = 197

x10[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x10[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x10 = x10.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x10['ID'] = 260

x11[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x11[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x11 = x11.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x11['ID'] = 525

x12[['x_mean', 'y_mean', 'z_mean', 'x_std', 'y_std', 'z_std', 'x_max', 'y_max', 'z_max', 'x_min', 'y_min', 'z_min', 'x_med', 'y_med', 'z_med']] = x12[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]]
x12 = x12.drop(labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14], axis=1)
x12['ID'] = 914

In [10]:
frames = x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12

In [11]:
UserDF = pd.concat(frames, axis=0, ignore_index=True)

In [12]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [13]:
UserDF

x_mean    y_mean    z_mean     x_std     y_std     z_std  x_max  \
0     0.865081 -0.023889  0.379051  0.190781  0.170309  0.199526  1.416   
1     0.917293 -0.023556  0.390091  0.266191  0.147141  0.197728  1.524   
2     0.896717 -0.015990  0.403960  0.242456  0.187935  0.234538  1.425   
3     0.912323 -0.014525  0.390970  0.245128  0.153568  0.224908  1.479   
4     0.927859 -0.037667  0.381505  0.220609  0.197882  0.220970  1.475   
...        ...       ...       ...       ...       ...       ...    ...   
4260  0.899960 -0.053626  0.419172  0.260252  0.184183  0.255411  1.431   
4261  0.907071 -0.045535  0.415949  0.248308  0.191236  0.242951  1.489   
4262  0.890545 -0.028495  0.391646  0.251432  0.159956  0.240598  1.439   
4263  0.875303 -0.047566  0.366081  0.249060  0.175357  0.210105  1.442   
4264  0.866152 -0.045879  0.372293  0.255528  0.186167  0.215546  1.500   

      y_max  z_max  x_min  y_min  z_min  x_med  y_med  z_med   ID  
0     0.380  1.066  0.525 -0.386  0.082  0.829 -0.018  0.346  128  
1     0.294  0.962  0.509 -0.346  0.041  0.908 -0.021  0.312  128  
2     0.558  1.007  0.512 -0.376 -0.002  0.874 -0.005  0.361  128  
3     0.364  1.131  0.521 -0.433  0.062  0.885 -0.013  0.341  128  
4     0.688  1.100  0.494 -0.439  0.050  0.905 -0.019  0.325  128  
...     ...    ...    ...    ...    ...    ...    ...    ...  ...  
4260  0.263  1.010  0.515 -0.589 -0.007  0.832 -0.009  0.345  914  
4261  0.443  0.996  0.486 -0.592  0.085  0.845 -0.008  0.349  914  
4262  0.351  0.973  0.542 -0.538  0.037  0.779 -0.020  0.298  914  
4263  0.435  0.952  0.538 -0.625  0.026  0.773 -0.016  0.318  914  
4264  0.494  0.979  0.484 -0.701  0.085  0.775 -0.003  0.283  914  

[4265 rows x 16 columns]

In [14]:
X = UserDF.drop(labels='ID', axis=1)
y = UserDF['ID']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
svm = svm.SVC(C=70.0, random_state=42)

In [17]:
model = svm.fit(X_train, y_train)

In [18]:
preds = svm.predict(X_test)

In [19]:
print(confusion_matrix(y_test, preds))

[[83  0  0  3  1  0  0  0  0  5  0  0]
 [ 0 67  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 72  0  0  5  0  0  0  0  0  0]
 [ 3  0  0 66  1  0  0  0  0  1  0  0]
 [ 1  0  0  0 68  0  0  1  0  0  0  0]
 [ 0  0  3  0  0 62  0  0  0  0  1  0]
 [ 0  0  0  0  0  0 66  0  0  0  0  0]
 [ 0  0  0  0  1  0  0 74  0  0  0  0]
 [ 0  0  0  0  0  0  0  1 44  0  1  0]
 [ 4  0  0  0  0  0  0  0  0 65  0  0]
 [ 1  1  0  0  0  1  0  0  0  0 76  0]
 [ 2  0  0  0  0  0  0  0  0  2  0 71]]


In [20]:
print(accuracy_score(y_test, preds) * 100)

95.42790152403282


In [21]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

         128       0.88      0.90      0.89        92
         129       0.99      1.00      0.99        67
         143       0.96      0.94      0.95        77
         153       0.96      0.93      0.94        71
         154       0.96      0.97      0.96        70
         162       0.91      0.94      0.93        66
         165       1.00      1.00      1.00        66
         177       0.97      0.99      0.98        75
         197       1.00      0.96      0.98        46
         260       0.89      0.94      0.92        69
         525       0.97      0.96      0.97        79
         914       1.00      0.95      0.97        75

    accuracy                           0.95       853
   macro avg       0.96      0.96      0.96       853
weighted avg       0.96      0.95      0.95       853

